import type { TestInfo } from '@playwright/test';

/**
 * An unmet ENVIRONMENT precondition skips locally and FAILS on CI.
 *
 * Locally these frontends and discovery files are opt-in: you run one project at
 * a time and the others aren't up, so skipping is what lets `--project=mock`
 * work on a laptop. On CI every one of them is started or generated by the
 * workflow, so "it isn't there" doesn't mean "not applicable" — it means the
 * workflow broke. Skipping then reports a green run that tested nothing, which
 * is the one failure mode CI cannot afford: block-sanity had stopped running
 * entirely in the nextjs job (no DISCOVER_BLOCKS_API in its env) and said
 * "3 skipped" while the job went green.
 *
 * For ENVIRONMENT preconditions only. A deliberate scope rule — "this spec only
 * applies to mock/nuxt/nextjs" — stays an ordinary skip, because nothing is
 * broken and no CI change could make that test run.
 *
 * @param testInfo - the running test's info (for the local skip)
 * @param met - is the precondition satisfied
 * @param reason - what is missing, phrased so a CI failure names the fix
 */
export function requireEnvironment(
  testInfo: TestInfo,
  met: boolean,
  reason: string,
): void {
  if (met) return;
  if (process.env.CI) {
    throw new Error(
      `Environment precondition not met on CI: ${reason}. ` +
        `On CI this is a workflow fault, not a reason to skip — the tests it ` +
        `guards would silently not run.`,
    );
  }
  testInfo.skip(true, reason);
}

/**
 * Why `url` can't be fetched, or null when it answers 2xx. Says WHY — a bare
 * "not reachable" hid a server that was up on the other address family (in a
 * container `localhost` is both 127.0.0.1 and ::1), which curl reached and
 * Node's fetch didn't.
 */
export async function unreachable(url: string): Promise<string | null> {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(2000) });
    return res.ok ? null : `HTTP ${res.status}`;
  } catch (err) {
    // fetch rejects with a TypeError on a network failure (the cause holds the
    // errno) and a DOMException when the timeout aborts it.
    if (!(err instanceof TypeError || err instanceof DOMException)) throw err;
    const cause = (err as { cause?: { code?: string; message?: string } }).cause;
    return `${err.name}: ${cause?.code ?? cause?.message ?? err.message}`;
  }
}
